### ISSUE TITLE
Generated cop refers to a dead link

### ISSUE THREAD

**Issue by Morozzzko** [rubocop-hq/rubocop-extension-generator#11]
I've generated a new project using extension generator. Then I generated a cop using `bundle exec rake new_cop[Domain/Cop]`

It generated a file `lib/rubocop/cop/domain/cop.rb` and it had those lines:

```ruby
      class Cop < Base
        # TODO: Implement the cop in here.
        #
        # In many cases, you can use a node matcher for matching node pattern.
        # See https://github.com/rubocop-hq/rubocop-ast/blob/master/lib/rubocop/node_pattern.rb
        #
        # For example

```

However, the link https://github.com/rubocop-hq/rubocop-ast/blob/master/lib/rubocop/node_pattern.rb returns 404

**Comment by andyw8** [comment]
Thanks, looks like it's been moved to `https://github.com/rubocop-hq/rubocop-ast/blob/master/lib/rubocop/ast/node_pattern.rb` – a PR to correct this would be welcome.

**Comment by Morozzzko** [comment]
I resolved it via https://github.com/rubocop-hq/rubocop/pull/8651
